##datasouce->mysql
spring:
  datasource:
    url: jdbc:mysql://192.168.0.239:3306/blog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
##orm->hibernet
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
##app name
  application:
    name: service-user
    
##register  eureka server
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
##log      
logging:
  path: D:\\logs\\service-user
  level:
    root: ERROR
    com.user.web: INFO
  
   
##http server
server:
  port: 8081
  context-path: /user
    